# https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/gae/app-engine.yml
on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - main

name: Deploy to Google App Engine

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Update Env. Variables
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
          GCP_SERVICE_ACCOUNT_INFO: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
#          version: v1
